batch_size: 1
trajectory_len: 1
mask_input_channel: False
max_step: 30

# Test with ckpt trained on full dataset (trained only on doors is too small a dataset)
generator_ckpt: ${hydra:runtime.cwd}/ckpts/generator/articulated.ckpt
verifier_ckpt: ${hydra:runtime.cwd}/ckpts/verifier/articulated.ckpt