name: articulated
task: articulated

data_dir: ${oc.env:HOME}/datasets/partnet-mobility # Change to your partnet-mobility dataset path
toy_dataset_path: null  # if general articulated objects

special_req: half-half
lr: 1e-3
mask_input_channel: True
randomize_camera: True
randomize_size: False
augmentation: False
seed: 42
n_points: 1200
