name: articulated
data_dir: ${oc.env:HOME}/datasets/partnet-mobility
toy_dataset_path: None  # if general articulated objects

lr: 1e-3
mask_input_channel: True
randomize_camera: True
randomize_size: False
augmentation: False
seed: 42
n_points: 1200
