name: multimodal_door
task: articulated

data_dir: ${oc.env:HOME}/datasets/failure_history_door # Change to your generated multimodal door dataset path
toy_dataset_path: ${hydra:runtime.cwd}/configs/dataset/multimodal_door.json

special_req: half-half
lr: 1e-3
mask_input_channel: True
randomize_camera: True
randomize_size: False
augmentation: False
seed: 42
n_points: 1200
