name: uneven_object
task: uneven

data_dir: ${oc.env:HOME}/datasets/unevenobject # Change to your generated uneven object dataset path
toy_dataset_path: ${hydra:runtime.cwd}/configs/dataset/uneven_object.json

special_req: "torque"
mask_input_channel: True
randomize_camera: False
randomize_size: False
augmentation: False
seed: 42
n_points: 1200