name: trajectory_diffuser_hispndit
lr: 1e-4
lr_warmup_steps: 100
batch_size: 128
epochs: 1000
train_sample_number : None # To be filled in train.py
check_val_every_n_epoch: 5 # 20
trajectory_len: 1
mode: delta
wta: True
wta_trial_times: 20
